import { ReactNode, FC } from "react";
import Head from "next/head";
import { Container } from "@mui/material";
import ResponsiveAppBar from "@/components/Topbar";

import Profile from "@/components/Profile";
import Updater from "@/components/Updater";

const Layout: FC<{ children?: ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Updater />
      <ResponsiveAppBar />
      <Container
        maxWidth="xl"
        sx={{
          py: 5,
        }}
      >
        <Profile />
        {children}
      </Container>
    </>
  );
};

export default Layout;
